name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Defalt
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./Defalt
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      working-directory: ./Defalt
